function camera(num);
videoObj=videoinput('winvideo',1,'RGB24_1280x960');
set(videoObj, 'SelectedSourceName', 'input1');
set(videoObj, 'FramesPerTrigger', 1);
start(videoObj);
image = getdata(videoObj);
imshow(image);
imwrite(image, ['board' num2str(num) '.png']);
stop(videoObj);
delete(videoObj);